export const events = [
    {
        image: '/images/event1.png',
        title: 'Google I/O 2026',
        slug: 'google-io-2026',
        location: 'Mountain View, CA, USA',
        date: 'May 20, 2026',
        time: '10:00 AM PT',
    },
    {
        image: '/images/event2.png',
        title: 'Microsoft Build 2026',
        slug: 'microsoft-build-2026',
        location: 'Seattle, WA, USA',
        date: 'May 19, 2026',
        time: '9:00 AM PT',
    },
    {
        image: '/images/event3.png',
        title: 'React Summit 2026',
        slug: 'react-summit-2026',
        location: 'Amsterdam, Netherlands',
        date: 'June 12, 2026',
        time: '9:30 AM CEST',
    },
    {
        image: '/images/event4.png',
        title: 'Hack the North 2026',
        slug: 'hack-the-north-2026',
        location: 'Waterloo, ON, Canada',
        date: 'September 18, 2026',
        time: '8:00 AM ET',
    },
    {
        image: '/images/event5.png',
        title: 'KubeCon + CloudNativeCon North America 2026',
        slug: 'kubecon-cloudnativecon-na-2026',
        location: 'Austin, TX, USA',
        date: 'November 10, 2026',
        time: '9:00 AM CT',
    },
    {
        image: '/images/event6.png',
        title: 'PyCon US 2026',
        slug: 'pycon-us-2026',
        location: 'Pittsburgh, PA, USA',
        date: 'April 15, 2026',
        time: '8:30 AM ET',
    },
];